### ISSUE TITLE
Button interact to join Parkour forwards an extra click event, opening the Options menu.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#20]
**Describe the bug**
I have a button setup at my spawn to join the parkour mode. Upon right clicking the button, it runs the command ``/parkour join``. However if players right click the button while their inventory slot is hovering over slot 9, WITP opens the options menu immediately on join as if the player right clicked the Options item when they only interacted with a button prior (single right click).

I have tested this with two separate plugins that handle attaching commands to run on interact with a button; ServerSigns & ButtonWarps.

**To Reproduce**
Steps to reproduce the behavior with ServerSigns
1. Place button on a wall.
2. ``/svs add parkour join``
3. Right click to attach command.
4. Right click button to join WITP while hovering over slot 9.
5. Options menu opens on join.

Steps to reproduce the behavior with ButtonWarps
1. Place button on a wall.
2. ``/bw make parkourtest nowhere``
3. ``/bw cmd parkourtest add parkour join``
4. Stare at button.
5. ``/bw link parkourtest``
6. Right click button to join WITP while hovering over slot 9.
7. Options menu opens on join.

**Errors**
None.

**Versions**
- Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/2f21af98ebc02d0df37b80ae981382070c839566
- Paper dev 467

**Additional context**
I also tried binding the command ``/parkour join`` to an NPC from Citizens. NPC interact doesn't seem to have this problem, only buttons when you right click prior to joining.

**Comment by Efnilite** [comment]
Should be fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/11789e232b529465770513c7334f085cdc87c9fd

**Comment by mibby** [comment]
@Efnilite This is not fixed for me. Tested compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/a6ac5cf068ad2f5abfd6c1eb29d194d0e6d0c63d

**Comment by mibby** [comment]
Could a workaround be to not register the options menu function until a couple ticks after joining?

**Comment by Efnilite** [comment]
Looks like I forgot this in 2.1, I'll add it in 2.2 (sorry)

**Comment by Efnilite** [comment]
Fixed in latest commit.

**Comment by mibby** [comment]
This is not fixed for me as of v2.1a - Hotfix 10.

**Comment by Efnilite** [comment]
I forgot to push the commit, it should be fixed now (oops)

**Comment by mibby** [comment]
Seems to be working, thanks. The character makes a weird motion like they attempted a right click after teleport, but it's better than the GUI being opened.
